// Generates the homepage breadth block (#services inner) from data/projects.json.
// The founder's complaint 2026-09-07 was that the site read as a single-industry
// (quarry) shop. The fix is structural: the range comes from the data, so adding
// a project to projects.json puts it on the homepage. Never hand-edit the block
// between the BREADTH markers in site/index.html -- edit this and re-run.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const { projects } = JSON.parse(readFileSync(path.join(ROOT, "data/projects.json"), "utf8"));

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// One row per build. `named:false` renders the descriptor, never the client.
const rows = projects.map((p, i) => {
  const title = p.named ? p.name : p.headline;
  const note  = p.named ? p.headline : (p.what || "").split(".")[0] + ".";
  const years = p.years || "";
  return `        <li class="ix-row rv">
          <span class="ix-n">${String(i + 1).padStart(3, "0")}</span>
          <span class="ix-build"><b>${esc(title)}</b><span class="ix-note">${esc(note)}</span></span>
          <span class="ix-sector">${esc(p.sector || "")}</span>
          <span class="ix-years">${esc(years)}</span>
        </li>`;
}).join("\n");

// Full sector string, deduped. Do not truncate at the comma: it turned
// "Retail, hospitality and field service" into "Retail". The chips are the
// range argument, so they must say what the work actually was.
const sectors = [...new Set(projects.map(p => (p.sector || "").trim()).filter(Boolean))].sort();

const block = `
    <span class="label">04 &middot; The index</span>
    <h2>The range is the argument.</h2>
    <p class="dim rv ix-lede">One line per build. No screenshots, no hero shots. Every one of these was designed, built and shipped by the same two partners and the agents they direct.</p>

    <ul class="ix-chips rv" aria-label="sectors we have shipped into">
${sectors.map(s => `      <li>${esc(s)}</li>`).join("\n")}
    </ul>

    <div class="ix-wrap">
      <ul class="ix">
${rows}
      </ul>
    </div>
    <p class="ix-foot rv"><span>Showing ${projects.length} of 374 repositories &middot; 41 programmes &middot; 2018&ndash;2026</span> <a href="/work">Open the full index &rarr;</a></p>
`;

const idx = path.join(ROOT, "site/index.html");
let html = readFileSync(idx, "utf8");
const A = "<!-- BREADTH:start (generated by scripts/genbreadth.mjs) -->";
const B = "<!-- BREADTH:end -->";
const i = html.indexOf(A), j = html.indexOf(B);
if (i === -1 || j === -1) { console.error("markers missing in site/index.html"); process.exit(1); }
// index splice, not a regex: the start marker contains parentheses.
html = html.slice(0, i) + A + block + "    " + html.slice(j);
writeFileSync(idx, html);
console.log(`breadth block written: ${projects.length} rows, ${sectors.length} sectors`);
