// Generates the homepage breadth block (#services inner) from data/projects.json.
// The founder's complaint 2026-09-07 was that the site read as a single-industry
// (quarry) shop. The fix is structural: the range comes from the data, so adding
// a project to projects.json puts it on the homepage. Never hand-edit the block
// between the BREADTH markers in site/index.html -- edit this and re-run.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const { projects } = JSON.parse(readFileSync(path.join(ROOT, "data/projects.json"), "utf8"));
// The studio's own declaration (founder, 2026-09-28): capabilities, industries
// and the KPI line. A new capability or industry is a data row, not an edit here.
const studio = JSON.parse(readFileSync(path.join(ROOT, "data/studio.json"), "utf8"));

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// One row per build. `named:false` renders the descriptor, never the client.
// Each row carries its authored pigment: colour is per-project DATA (the move
// Stripe Press makes), so range is visible as chromatic variety before a word
// is read. That is the answer to "it looks like we only did quarries".
const row = (p, i) => {
  const title = p.named ? p.name : p.headline;
  const note  = p.named ? p.headline : (p.what || "").split(".")[0] + ".";
  return `        <li class="ix-row rv" style="--pig:${p.pigment}">
          <span class="ix-n">${String(i + 1).padStart(3, "0")}</span>
          <span class="ix-build"><b>${esc(title)}</b><span class="ix-note">${esc(note)}</span></span>
          <span class="ix-sector"><i class="ix-dot" aria-hidden="true"></i>${esc(p.sector || "")}</span>
          <span class="ix-years">${esc(p.years || "undated")}</span>
        </li>`;
};
const rows = projects.map(row).join("\n");

// The hero strip leads with the PRODUCT CATEGORY, not the client. Founder,
// 2026-09-07: "project name or client name dont excite them ... need to brief
// the type of work, means technical product terms of them like P2P, D2C,
// E-com, O2C, or more than that". A buyer scanning for their own problem
// recognises "O2C · DISPATCH" and does not recognise "RockProsUSA".
const heroRows = studio.capabilities.map((c, i) => `        <li style="--pig:${["#0F8083", "#0b6366", "#1d1d1f", "#0F8083", "#0b6366", "#1d1d1f"][i % 6]}"><i aria-hidden="true"></i><b>${esc(c.name)}</b><span>${esc(c.note)}</span><em>${esc(c.proof)}</em></li>`).join("\n");

// KPI line. Every figure is derived, not asserted:
//   products  = rows in data/projects.json plus the 14 declared in genwork.mjs
//   sectors   = distinct declared families
//   repos     = the crawl total in data/portfolio-inventory.md
//   partners  = the two accountable partners; the one count set the site uses
//               everywhere is 34 / 9 / 374 (data/brain-narrative.md §5)
// Chips are FAMILIES the project declares, not raw sector strings. Deriving
// them from `sector` gave 20 chips for 20 projects, which is a dump wearing a
// chip's clothes. Each project names its family in data/projects.json, so a new
// project joins an existing chip instead of minting another one.
const families = [...new Set(projects.map((p) => p.family).filter(Boolean))].sort();
const missingFamily = projects.filter((p) => !p.family).map((p) => p.id);
if (missingFamily.length) { console.error(`projects missing family: ${missingFamily.join(", ")}`); process.exit(1); }

const KPI = studio.kpi;
const kpiBlock = KPI.map(([n, l]) => `        <li><b>${n}</b><span>${l}</span></li>`).join("\n");

// The studio home carries the RANGE, not the index: the 20-row list lives on
// /studio/work (content audit 2026-09-15, row 15: the home page was 2,400 words
// of other pages). Chips are derived from the data, so a new family shows up
// here on the next run without a hand edit.
const block = `
    <span class="label rv">03 &middot; The range</span>
    <h2 class="rv">25+ products. Six industries we know cold.</h2>
    <p class="dim rv ix-lede">The same two partners on every build, with AI doing the volume work.</p>

    <ul class="ix-chips rv" aria-label="industries we ship into">
${studio.industries.map(f => `      <li>${esc(f)}</li>`).join("\n")}
    </ul>
    <p class="ix-foot rv"><span>One line per build on the index.</span> <a href="/studio/work">Open the full index &rarr;</a></p>
`;

const heroBlock = `
      <ul class="hero-kpi" aria-label="delivery to date">
${kpiBlock}
      </ul>
      <ul class="hero-work" aria-label="what we do">
${heroRows}
      </ul>
      <p class="hero-work-foot"><a href="/studio/work">See the work &rarr;</a></p>
`;

const idx = path.join(ROOT, "site/studio/index.html");
let html = readFileSync(idx, "utf8");
const A = "<!-- BREADTH:start (generated by scripts/genbreadth.mjs) -->";
const B = "<!-- BREADTH:end -->";
const i = html.indexOf(A), j = html.indexOf(B);
if (i === -1 || j === -1) { console.error("markers missing in site/index.html"); process.exit(1); }
// index splice, not a regex: the start marker contains parentheses.
html = html.slice(0, i) + A + block + "    " + html.slice(j);

const HA = "<!-- HEROWORK:start (generated by scripts/genbreadth.mjs) -->";
const HB = "<!-- HEROWORK:end -->";
const hi = html.indexOf(HA), hj = html.indexOf(HB);
if (hi === -1 || hj === -1) { console.error("hero markers missing"); process.exit(1); }
html = html.slice(0, hi) + HA + heroBlock + "      " + html.slice(hj);
writeFileSync(idx, html);
console.log(`breadth block written: ${projects.length} rows, ${families.length} families`);
