// The capability index, DERIVED from the capability pages themselves.
//
// site/brain/capabilities/ holds one page per capability. A hand-maintained
// index over 34 of those is the failure mode this repo already knows: a list
// somebody has to remember to add a row to, which silently falls behind the
// day a page lands (measured 2026-09-12: the index linked 0 of 34).
//
// So the index is generated. Each page declares three things the generator
// reads, and nothing here needs editing when a page is added:
//   <span class="label">ACT</span>   the group, in the page hero
//   <h1>…</h1>                        the claim
//   <meta name="description">         the one-line summary
// The rows are written between the markers in the index page:
//   <!-- CAPINDEX:start --> … <!-- CAPINDEX:end -->
//
// A page whose group label is not one of GROUPS below is still listed, under
// "Everything else", rather than dropped. Falling out of the index silently is
// exactly what this file exists to prevent.
//
//   node scripts/gencapindex.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const DIR = path.join(import.meta.dirname, "..", "site", "brain", "capabilities");
const INDEX = path.join(DIR, "index.html");

// Order is the argument: what it notices, what it remembers, how it judges,
// what it does, what it may claim, what a CIO asks first.
const GROUPS = [
  ["SENSE", "What it notices without being asked"],
  ["RECALL", "One memory where there used to be five"],
  ["REASON", "Judgment, not rules"],
  ["ACT", "It does the work, and a person decides"],
  ["PROVE", "What it is allowed to claim"],
  ["CONNECT", "The parts a CIO asks about first"]
];

const strip = s => s.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();

function readPage(file) {
  const html = readFileSync(path.join(DIR, file), "utf8");
  // The hero label is the FIRST .label on the page; the section labels that
  // follow ("What it is", "How it works") must not win.
  const group = (html.match(/<span class="label">([^<]+)<\/span>/) || [])[1]?.trim().toUpperCase();
  const h1 = (html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/) || [])[1];
  const desc = (html.match(/<meta name="description" content="([^"]*)"/) || [])[1];
  if (!h1 || !desc) return null;
  return {
    slug: file.slice(0, -".html".length),
    group: group || "",
    // The h1 carries a <br> and an <span class="accent"> turn; the index wants
    // one line, so the markup is flattened rather than re-styled.
    claim: strip(h1),
    // First sentence only. A 200-character meta description in a grid cell
    // buries the next row.
    line: desc.split(/(?<=\.)\s/)[0]
  };
}

const pages = readdirSync(DIR)
  .filter(f => f.endsWith(".html") && f !== "index.html")
  .map(readPage)
  .filter(Boolean)
  .sort((a, b) => a.claim.localeCompare(b.claim));

const esc = s => s.replace(/&(?!(?:[a-z]+|#\d+);)/g, "&amp;");

function block(name) {
  const rows = pages.filter(p => p.group === name);
  if (!rows.length) return "";
  // The row marker is a COUNT, not the group name: the group is already the
  // heading above these rows, and repeating "ACT" seven times down the gutter
  // reads as noise (seen in a render, 2026-09-12).
  return rows.map((p, i) => `        <a class="svc rv" href="/brain/capabilities/${p.slug}">
          <span class="num">${String(i + 1).padStart(2, "0")}</span><h3>${esc(p.claim)}</h3>
          <p class="dim">${esc(p.line)}</p>
        </a>`).join("\n");
}

const known = new Set(GROUPS.map(g => g[0]));
const orphans = pages.filter(p => !known.has(p.group));

let out = GROUPS.map(([name, heading]) => {
  const rows = block(name);
  if (!rows) return "";
  return `      <div class="rv">
        <span class="label">${name}</span>
        <h2>${heading}</h2>
      </div>
${rows}`;
}).filter(Boolean).join("\n\n");

if (orphans.length) {
  out += `\n\n      <div class="rv">
        <span class="label">MORE</span>
        <h2>Everything else</h2>
      </div>
` + orphans.map(p => `        <a class="svc rv" href="/brain/capabilities/${p.slug}">
          <span class="num">${p.group || "—"}</span><h3>${esc(p.claim)}</h3>
          <p class="dim">${esc(p.line)}</p>
        </a>`).join("\n");
}

const html = readFileSync(INDEX, "utf8");
const marked = /<!-- CAPINDEX:start[^>]*-->[\s\S]*?<!-- CAPINDEX:end -->/;
if (!marked.test(html)) {
  console.error("No CAPINDEX markers in site/brain/capabilities/index.html — add:\n  <!-- CAPINDEX:start -->\n  <!-- CAPINDEX:end -->");
  process.exit(1);
}
writeFileSync(INDEX, html.replace(marked,
  `<!-- CAPINDEX:start (generated by scripts/gencapindex.mjs) -->\n${out}\n      <!-- CAPINDEX:end -->`));

console.log(`gencapindex: ${pages.length} capability pages indexed` +
  (orphans.length ? `, ${orphans.length} without a known group label` : ""));
for (const [name] of GROUPS) console.log(`  ${name}: ${pages.filter(p => p.group === name).length}`);
