// Studio hero (between the HEROWORK markers in site/studio/index.html).
// Split out of genbreadth.mjs 2026-09-29 so the animated hero has one owner.
// Images and copy come from data/studio.json (heroImages).
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const studio = JSON.parse(readFileSync(path.join(ROOT, "data/studio.json"), "utf8"));
const IMG = (f) => `/img/studio/${f}`;
const H = studio.heroImages;
const heroBlock = `
      <div class="mosaic">
        <figure class="m-a"><img src="${IMG(H.back)}" alt="CitySense, AI billboard campaign planner" width="1600" height="1000" decoding="async" fetchpriority="high"></figure>
        <figure class="m-b"><img src="${IMG(H.front)}" alt="CitedSpy, AI search visibility dashboard" width="1600" height="1000" decoding="async"></figure>
        <figure class="m-c"><img src="${IMG(H.third)}" alt="RockPros, quarry dispatch board" width="1600" height="1000" decoding="async"></figure>
      </div>
`;
const idx = path.join(ROOT, "site/studio/index.html");
let html = readFileSync(idx, "utf8");
const HA = "<!-- HEROWORK:start (generated by scripts/genbreadth.mjs) -->";
const HB = "<!-- HEROWORK:end -->";
const hi = html.indexOf(HA), hj = html.indexOf(HB);
if (hi === -1 || hj === -1) { console.error("hero markers missing"); process.exit(1); }
html = html.slice(0, hi) + HA + heroBlock + "      " + html.slice(hj);
writeFileSync(idx, html);
console.log("studio hero written");
