// Per-page SEO block, DERIVED from the page and the route, injected between
//
//     <!-- SEO:start (generated by scripts/genseo.mjs) --> … <!-- SEO:end -->
//
// in every page head. Idempotent: the block is rebuilt from scratch on every run
// and nothing outside the markers is touched. Nothing a page already declares is
// duplicated: og:image, twitter:image, the robots meta, an Organization or a
// BreadcrumbList already in the head are detected (outside the block) and skipped.
// A canonical is never written here, so a second canonical is impossible.
//
// What the block carries, per page:
//   <meta name="robots" content="index,follow">
//   <meta property="og:image">, <meta name="twitter:image">   -> /og.png
//   <meta name="author">                                       (static, the studio)
//   <meta property="article:modified_time">                    only with --modified=YYYY-MM-DD
//   BreadcrumbList JSON-LD  -> from the page's own .crumb when it has one, else
//                              from the route's ancestors that exist as pages
//   Organization JSON-LD    -> one declaration, below; sameAs carries only URLs
//                              the site itself states (workelate.com, the mail address)
//
//   node scripts/genseo.mjs                       every page under site/, in place
//   node scripts/genseo.mjs --dry                 report only, write nothing
//   node scripts/genseo.mjs --modified=2026-09-15 also stamp article:modified_time
//   node scripts/genseo.mjs path/to/copy.html     only these files (a file outside
//                                                 site/ takes its route from its canonical)
// Run it LAST, after genchrome and every page generator, before gensitemap.
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";

const SITE = path.join(import.meta.dirname, "..", "site");
const ORIGIN = "https://aina.workelate.com";
const OG_IMAGE = `${ORIGIN}/og.png`;
const MARK = "SEO";

// ---- the one Organization declaration ------------------------------------
// sameAs: ONLY what the site states in public. workelate.com is named as the
// parent on every page; the mail address sits in every footer. No social URLs
// are invented here: add one only when a page links it.
const ORGANIZATION = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "WorkElate Excellence Studio",
  "alternateName": ["WE_AINA", "WorkElate's AI-Native Studio"],
  "url": `${ORIGIN}/`,
  "logo": `${ORIGIN}/img/workelate-logo.svg`,
  "email": "chitransh@workelate.com",
  // The one product definition, word for word the sentence in site/llms.txt.
  "description": "WorkElate Chief, the Brain, is one memory across the systems a 200 to 2,000 person company already runs, made by WorkElate and installed by WE_AINA, WorkElate's own studio: it reads what your CRM, mail, tickets and documents already record, judges what needs a person, and asks before it changes anything.",
  "parentOrganization": { "@type": "Organization", "name": "WorkElate", "url": "https://www.workelate.com/" },
  "founder": [
    { "@type": "Person", "name": "Chitransh" },
    { "@type": "Person", "name": "Pratik" }
  ],
  "sameAs": ["https://www.workelate.com/"]
};

// ---- helpers ---------------------------------------------------------------
function pages(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (name.startsWith(".")) continue;
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) pages(p, out);
    else if (name.endsWith(".html")) out.push(p);
  }
  return out;
}
function routeOf(file) {
  const rel = path.relative(SITE, file).split(path.sep);
  const last = rel[rel.length - 1];
  if (last === "index.html") rel.pop();
  else rel[rel.length - 1] = last.slice(0, -".html".length);
  return "/" + rel.join("/");
}
const decode = s => s.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, " ").replace(/&middot;/g, "·").replace(/&rsquo;/g, "’");
const text = s => decode(s.replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();
const attr = (tag, name) => { const m = tag.match(new RegExp(`\\s${name}\\s*=\\s*("([^"]*)"|'([^']*)')`, "i")); return m ? decode(m[2] ?? m[3]) : null; };
const hasMeta = (head, sel) => new RegExp(`<meta[^>]*\\s(?:name|property)\\s*=\\s*["']${sel}["']`, "i").test(head);
const hasLdType = (head, type) => {
  for (const m of head.matchAll(/<script[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)) {
    try {
      const j = JSON.parse(m[1]);
      const arr = Array.isArray(j) ? j : (j["@graph"] || [j]);
      if (arr.some(o => o && o["@type"] === type)) return true;
    } catch { /* an invalid block does not count as declaring anything */ }
  }
  return false;
};
const blockRe = new RegExp(`\\n?<!-- ${MARK}:start[^>]*-->[\\s\\S]*?<!-- ${MARK}:end -->`, "g");
const stripBlock = html => html.replace(blockRe, "");

// Short label for a route, derived from the page that serves it: its og:title
// when that is short, else its <title> minus the ", WE_AINA" suffix, cut at the
// first comma. A route with no page gets its slug humanised.
function labelOf(route, cache) {
  if (cache.has(route)) return cache.get(route);
  const file = route === "/" ? path.join(SITE, "index.html") : (existsSync(path.join(SITE, route + ".html")) ? path.join(SITE, route + ".html") : path.join(SITE, route, "index.html"));
  let label = null;
  if (existsSync(file)) {
    const head = (readFileSync(file, "utf8").match(/<head[\s\S]*?<\/head>/i) || [""])[0];
    const t = text((head.match(/<title>([\s\S]*?)<\/title>/i) || [, ""])[1]).replace(/,?\s*WE_AINA\s*$/, "");
    label = t.split(/,|·|:/)[0].trim() || null;
  }
  if (!label) label = route.split("/").pop().replace(/-/g, " ").replace(/^\w/, c => c.toUpperCase());
  cache.set(route, label);
  return label;
}

// Breadcrumb trail = the route's ancestors that exist as pages, plus the page.
// Names come from the page's own .crumb where it links the ancestor, else from
// the ancestor's title. The page itself is named from its own crumb tail or title.
function breadcrumbs(route, html, cache) {
  if (route === "/") return null;
  const segs = route.split("/").filter(Boolean);
  const trail = [];
  for (let i = 1; i < segs.length; i++) {
    const r = "/" + segs.slice(0, i).join("/");
    if (existsSync(path.join(SITE, r + ".html")) || existsSync(path.join(SITE, r, "index.html"))) trail.push(r);
  }
  trail.push(route);
  if (trail.length < 2) return null;              // a one-item trail says nothing
  const names = new Map();
  const crumb = html.match(/<(?:p|nav) class="crumb"[^>]*>([\s\S]*?)<\/(?:p|nav)>/i);
  if (crumb) {
    const parts = crumb[1].split(/\s\/\s/);
    for (const part of parts) {
      const a = part.match(/<a[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/i);
      if (a) names.set(a[1].replace(/\/+$/, "") || "/", text(a[2]));
    }
    const tail = text(parts[parts.length - 1]);
    if (tail && !/^vs\s/i.test(tail) && !names.has(route) && !parts[parts.length - 1].includes("<a")) names.set(route, tail);
  }
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": trail.map((r, i) => ({
      "@type": "ListItem", "position": i + 1,
      "name": names.get(r) || labelOf(r, cache),
      "item": `${ORIGIN}${r}`
    }))
  };
}

const ld = obj => `<script type="application/ld+json">\n${JSON.stringify(obj, null, 1)}\n</script>`;

export function seoBlock(html, route, { modified = null, cache = new Map() } = {}) {
  const bare = stripBlock(html);
  const head = (bare.match(/<head[\s\S]*?<\/head>/i) || [""])[0];
  const lines = [];
  const skipped = [];
  if (hasMeta(head, "robots")) skipped.push("robots"); else lines.push(`<meta name="robots" content="index,follow">`);
  if (hasMeta(head, "og:image")) skipped.push("og:image"); else lines.push(`<meta property="og:image" content="${OG_IMAGE}">`);
  if (hasMeta(head, "twitter:image")) skipped.push("twitter:image"); else lines.push(`<meta name="twitter:image" content="${OG_IMAGE}">`);
  if (hasMeta(head, "author")) skipped.push("author"); else lines.push(`<meta name="author" content="WE_AINA, WorkElate Excellence Studio">`);
  if (modified) {
    if (hasMeta(head, "article:modified_time")) skipped.push("article:modified_time");
    else lines.push(`<meta property="article:modified_time" content="${modified}">`);
  }
  const bc = breadcrumbs(route, bare, cache);
  if (hasLdType(head, "BreadcrumbList")) skipped.push("BreadcrumbList"); else if (bc) lines.push(ld(bc));
  if (hasLdType(head, "Organization")) skipped.push("Organization"); else lines.push(ld(ORGANIZATION));
  const block = `<!-- ${MARK}:start (generated by scripts/genseo.mjs) -->\n${lines.join("\n")}\n<!-- ${MARK}:end -->`;
  if (!/<\/head>/i.test(bare)) return { html: null, skipped, error: "no </head>" };
  const out = bare.replace(/<\/head>/i, `${block}\n</head>`);
  return { html: out, skipped, crumbs: bc ? bc.itemListElement.map(x => x.name) : null };
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const dry = args.includes("--dry");
  const modified = (args.find(a => a.startsWith("--modified=")) || "").slice("--modified=".length) || null;
  if (modified && !/^\d{4}-\d{2}-\d{2}$/.test(modified)) { console.error("--modified must be YYYY-MM-DD"); process.exit(2); }
  const files = args.filter(a => !a.startsWith("--")).map(f => path.resolve(f));
  const targets = files.length ? files : pages(SITE);
  const cache = new Map();
  let changed = 0, same = 0, failed = 0;
  for (const file of targets) {
    const html = readFileSync(file, "utf8");
    const inside = !path.relative(SITE, file).startsWith("..");
    let route;
    if (inside) route = routeOf(file);
    else {
      const canon = (html.match(/<link[^>]*rel\s*=\s*["']canonical["'][^>]*>/i) || [""])[0];
      const href = attr(canon, "href") || "";
      route = href.startsWith(ORIGIN) ? (href.slice(ORIGIN.length).replace(/\/+$/, "") || "/") : "/";
    }
    const { html: out, skipped, crumbs, error } = seoBlock(html, route, { modified, cache });
    if (error) { failed++; console.error(`genseo: ${file}: ${error}`); continue; }
    const status = out === html ? "same" : "write";
    if (status === "same") same++; else changed++;
    console.log(`${dry ? "dry " : ""}${status.padEnd(5)} ${route.padEnd(48)} crumbs=${crumbs ? crumbs.join(" › ") : "-"}${skipped.length ? "  skipped(already present): " + skipped.join(",") : ""}`);
    if (!dry && status === "write") writeFileSync(file, out);
  }
  console.log(`genseo: ${targets.length} pages, ${changed} ${dry ? "would change" : "written"}, ${same} unchanged, ${failed} failed`);
}
